import Header from "@/components/Header";
import LegalLayout from "@/components/legal/LegalLayout";

const Terms = () => (
  <div className="min-h-screen bg-background">
    <Header />
    <LegalLayout title="Terms & Conditions" updated="14 September 2026">
      <p>
        These terms govern your use of FlavorAI. By creating an account or using the site you agree
        to them.
      </p>

      <h2>The service provider</h2>
      <p>
        FlavorAI is provided by <strong>[LEGAL ENTITY NAME]</strong>,{" "}
        <strong>[REGISTERED BUSINESS ADDRESS]</strong>. Contact:{" "}
        <strong>[SUPPORT EMAIL]</strong>.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must give an accurate email address and keep your login details private.</li>
        <li>You are responsible for activity that happens under your account.</li>
        <li>You must be at least 13 years old to use FlavorAI.</li>
      </ul>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not attempt to break, overload or reverse-engineer the service.</li>
        <li>Do not scrape or resell the recipe content in bulk.</li>
        <li>Do not use the service to create unlawful, harmful or deceptive content.</li>
      </ul>
      <p>
        We apply request limits to keep the service stable and may suspend accounts that abuse it.
      </p>

      <h2>AI-generated content and food safety</h2>
      <p>
        Recipes, nutrition figures and images on FlavorAI are generated by AI and are provided for
        general information only. They are not medical, dietary or allergy advice. Always check
        ingredients against your own allergies and dietary needs, and follow safe cooking and food
        storage practice. Nutrition values are estimates and may be inaccurate.
      </p>

      <h2>Content ownership</h2>
      <p>
        The FlavorAI name, design and software remain ours. You may use generated recipes for your
        own personal cooking. Any text or ingredient lists you submit remain yours; you grant us
        permission to process them in order to provide the service.
      </p>

      <h2>Availability</h2>
      <p>
        We aim to keep FlavorAI available but we do not guarantee uninterrupted service. Features may
        change or be withdrawn.
      </p>

      <h2>Liability</h2>
      <p>
        To the extent permitted by law, we are not liable for indirect or consequential loss, or for
        any outcome arising from following an AI-generated recipe. Nothing in these terms limits
        liability that cannot be limited by law.
      </p>

      <h2>Ending your use</h2>
      <p>
        You can stop using FlavorAI and request account deletion at any time by writing to{" "}
        <strong>[SUPPORT EMAIL]</strong>. We may suspend or close accounts that breach these terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of <strong>[GOVERNING JURISDICTION]</strong>, and
        disputes will be handled by the courts of that jurisdiction.
      </p>
    </LegalLayout>
  </div>
);

export default Terms;
